DROP TABLE IF EXISTS INFORMATION;

CREATE TABLE INFORMATION(
		 ID_CUSTOMER BIGINT AUTO_INCREMENT NOT NULL,
		 NAME VARCHAR(255) NULL,
		 PHONE INT NULL,
		 EMAIL VARCHAR(255) NULL,
		 NAMERECIPE VARCHAR(255) NULL,
		 INGREDIENTS LONGTEXT  NULL,
		 RECIPE LONGTEXT  NULL,
		 TIME VARCHAR(255) NULL,
		 QUANTITY VARCHAR(255) NULL,
         PRIMARY KEY (ID_CUSTOMER));